THEMES = {
    "light": {
        "bg": "#f5f6fa",
        "fg": "#222831",
        "accent": "#1976d2",
        "sidebar": "#e3e6ee",
        "button": "#1976d2",
        "button_fg": "#ffffff",
        "entry_bg": "#ffffff",
        "entry_fg": "#222831",
        "listbox_bg": "#f5f6fa",
        "listbox_fg": "#222831",
        "select_bg": "#1976d2",
        "select_fg": "#ffffff",
    },
    "dark": {
        "bg": "#23272e",
        "fg": "#eeeeee",
        "accent": "#00adb5",
        "sidebar": "#1a1d23",
        "button": "#00adb5",
        "button_fg": "#23272e",
        "entry_bg": "#23272e",
        "entry_fg": "#eeeeee",
        "listbox_bg": "#23272e",
        "listbox_fg": "#eeeeee",
        "select_bg": "#00adb5",
        "select_fg": "#23272e",
    },
}
